services:
  - type: web
    name: flutter-jobs-ch
    env: docker          # Utilisation de Docker au lieu de Node
    region: frankfurt
    plan: free
    
    # Avec Docker, on n'a plus besoin de buildCommand ni startCommand ici
    # car ils sont définis dans le Dockerfile
    
    healthCheckPath: /api/health   # Plus robuste car ne dépend pas de la DB
    
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SCRAPE_SECRET
        generateValue: true
